name: Sihong Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Debug Information
        run: |
          echo "WAKATIME_API_KEY starts with: ${WAKATIME_API_KEY:0:3}"
          echo "GH_TOKEN starts with: ${GH_TOKEN:0:3}"
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: WakaReadme DevMetrics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
